'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { Menu, X, Heart } from 'lucide-react';

export const Header: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);

    const navItems = [
        { label: 'Inicio', href: '/' },
            { label: 'Historia', href: '/historia' },
                { label: 'Noticias', href: '/noticias' },
                    { label: 'Horarios', href: '/horarios' },
                        { label: 'Peticiones', href: '/peticiones' },
                          ];

                            return (
                                <header className="sticky top-0 z-50 bg-white shadow-md">
                                      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                                              <div className="flex items-center justify-between h-20">
                                                        <Link href="/" className="flex items-center gap-3 group">
                                                                    <motion.div
                                                                                  className="text-2xl font-bold text-primary-dark"
                                                                                                whileHover={{ scale: 1.1, rotate: 5 }}
                                                                                                              whileTap={{ scale: 0.95 }}
                                                                                                                          >
                                                                                                                                        [P]
                                                                                                                                                    </motion.div>
                                                                                                                                                                <div className="hidden sm:block">
                                                                                                                                                                              <h1 className="text-lg font-bold text-primary-dark group-hover:text-primary transition">
                                                                                                                                                                                              Parroquia
                                                                                                                                                                                                            </h1>
                                                                                                                                                                                                                          <p className="text-xs text-gray-600">Santa Maria de la Asuncion</p>
                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                          <nav className="hidden md:flex items-center gap-8">
                                                                                                                                                                                                                                                                      {navItems.map((item) => (
                                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                                                    key={item.href}
                                                                                                                                                                                                                                                                                                                    href={item.href}
                                                                                                                                                                                                                                                                                                                                    className="text-gray-700 hover:text-primary-dark font-medium transition relative group"
                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                  {item.label}
                                                                                                                                                                                                                                                                                                                                                                                  <span className="absolute bottom-0 left-0 w-0 h-0.5 bg-accent-gold group-hover:w-full transition-all duration-300" />
                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                      </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="hidden sm:flex items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                            <motion.button
                                                                                                                                                                                                                                                                                                                                                                                                                                                          whileHover={{ scale: 1.05 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        whileTap={{ scale: 0.95 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="flex items-center gap-2 px-4 py-2 bg-accent-gold text-primary-dark font-semibold rounded-lg hover:bg-yellow-300 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Heart className="w-5 h-5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Donar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </motion.button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setIsOpen(!isOpen)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="md:hidden p-2 hover:bg-gray-100 rounded-lg transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {isOpen ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <X className="w-6 h-6 text-primary-dark" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Menu className="w-6 h-6 text-primary-dark" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {isOpen && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <motion.nav
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                initial={{ opacity: 0, y: -10 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            animate={{ opacity: 1, y: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        exit={{ opacity: 0, y: -10 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="md:hidden pb-4 space-y-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {navItems.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        key={item.href}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        href={item.href}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="block px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setIsOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {item.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button className="w-full px-4 py-2 bg-accent-gold text-primary-dark font-semibold rounded-lg hover:bg-yellow-300 transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Donar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </motion.nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
