'use client';

import React, { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/hooks/useAuth';
import { motion } from 'framer-motion';
import Link from 'next/link';
import { LogOut, FileText, Clock, Heart } from 'lucide-react';
import { Button } from '@/components/common/Button';

export default function AdminPage() {
  const router = useRouter();
    const { isAuthenticated, usuario, logoutUser } = useAuth();

      useEffect(() => {
          if (!isAuthenticated) {
                router.push('/admin/login');
                    }
                      }, [isAuthenticated, router]);

                        if (!isAuthenticated) {
                            return null;
                              }

                                const adminItems = [
                                    {
                                          icon: FileText,
                                                title: 'Gestionar Noticias',
                                                      description: 'Crear, editar y eliminar noticias',
                                                            href: '/admin/noticias',
                                                                  color: 'from-blue-500 to-blue-600',
                                                                      },
                                                                          {
                                                                                icon: Clock,
                                                                                      title: 'Horarios de Misas',
                                                                                            description: 'Actualizar horarios y confesiones',
                                                                                                  href: '/admin/horarios',
                                                                                                        color: 'from-purple-500 to-purple-600',
                                                                                                            },
                                                                                                                {
                                                                                                                      icon: Heart,
                                                                                                                            title: 'Peticiones de Oracion',
                                                                                                                                  description: 'Gestionar intenciones de oracion',
                                                                                                                                        href: '/admin/peticiones',
                                                                                                                                              color: 'from-red-500 to-red-600',
                                                                                                                                                  },
                                                                                                                                                    ];
                                                                                                                                                    
                                                                                                                                                      return (
                                                                                                                                                          <div className="min-h-screen bg-gray-100">
                                                                                                                                                                <header className="bg-primary-dark text-white shadow-lg">
                                                                                                                                                                        <div className="max-w-7xl mx-auto px-4 py-6 flex items-center justify-between">
                                                                                                                                                                                  <div>
                                                                                                                                                                                              <h1 className="text-3xl font-bold">Panel de Administracion</h1>
                                                                                                                                                                                                          <p className="text-gray-300">Bienvenido, {usuario?.username}</p>
                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                              <Button
                                                                                                                                                                                                                                          variant="gold"
                                                                                                                                                                                                                                                      onClick={logoutUser}
                                                                                                                                                                                                                                                                  className="flex items-center gap-2"
                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                        <LogOut className="w-5 h-5" />
                                                                                                                                                                                                                                                                                                    Cerrar Sesion
                                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                            </header>
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                  <main className="max-w-7xl mx-auto px-4 py-12">
                                                                                                                                                                                                                                                                                                                                          <motion.div
                                                                                                                                                                                                                                                                                                                                                    initial={{ opacity: 0, y: 20 }}
                                                                                                                                                                                                                                                                                                                                                              animate={{ opacity: 1, y: 0 }}
                                                                                                                                                                                                                                                                                                                                                                        className="grid md:grid-cols-3 gap-6"
                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                          {adminItems.map((item, idx) => {
                                                                                                                                                                                                                                                                                                                                                                                                      const Icon = item.icon;
                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                                <Link key={item.href} href={item.href}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  initial={{ opacity: 0, y: 20 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    animate={{ opacity: 1, y: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      transition={{ delay: idx * 0.1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className={`bg-gradient-to-br ${item.color} text-white rounded-lg p-8 shadow-lg hover:shadow-xl transition cursor-pointer group`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          whileHover={{ y: -4 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Icon className="w-12 h-12 mb-4 group-hover:scale-110 transition" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3 className="text-2xl font-bold mb-2">{item.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-white text-opacity-90">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {item.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
