'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/hooks/useAuth';
import { motion } from 'framer-motion';
import { Button } from '@/components/common/Button';
import { Lock, User } from 'lucide-react';

export default function LoginPage() {
  const router = useRouter();
    const { isAuthenticated, loginUser, loading, error } = useAuth();
      const [username, setUsername] = useState('');
        const [password, setPassword] = useState('');

          useEffect(() => {
              if (isAuthenticated) {
                    router.push('/admin');
                        }
                          }, [isAuthenticated, router]);

                            const handleSubmit = async (e: React.FormEvent) => {
                                e.preventDefault();
                                    await loginUser(username, password);
                                      };

                                        return (
                                            <div className="min-h-screen bg-gradient-to-br from-primary-dark to-primary flex items-center justify-center px-4">
                                                  <motion.div
                                                          initial={{ opacity: 0, scale: 0.9 }}
                                                                  animate={{ opacity: 1, scale: 1 }}
                                                                          transition={{ duration: 0.5 }}
                                                                                  className="bg-white rounded-lg shadow-2xl p-8 max-w-md w-full"
                                                                                        >
                                                                                                <div className="text-center mb-8">
                                                                                                          <h1 className="text-3xl font-bold text-primary-dark">
                                                                                                                      Panel Admin
                                                                                                                                </h1>
                                                                                                                                          <p className="text-gray-600 mt-2">
                                                                                                                                                      Parroquia Santa Maria de la Asuncion
                                                                                                                                                                </p>
                                                                                                                                                                        </div>
                                                                                                                                                                        
                                                                                                                                                                                <form onSubmit={handleSubmit} className="space-y-4">
                                                                                                                                                                                          <div>
                                                                                                                                                                                                      <label className="block text-sm font-semibold text-gray-700 mb-2">
                                                                                                                                                                                                                    Usuario
                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                            <div className="relative">
                                                                                                                                                                                                                                                          <User className="absolute left-3 top-3 w-5 h-5 text-gray-400" />
                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                        type="text"
                                                                                                                                                                                                                                                                                                        value={username}
                                                                                                                                                                                                                                                                                                                        onChange={(e) => setUsername(e.target.value)}
                                                                                                                                                                                                                                                                                                                                        placeholder="admin"
                                                                                                                                                                                                                                                                                                                                                        className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-dark"
                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="block text-sm font-semibold text-gray-700 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                Contrasena
                                                                                                                                                                                                                                                                                                                                                                                                                                            </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Lock className="absolute left-3 top-3 w-5 h-5 text-gray-400" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="********"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-dark"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            initial={{ opacity: 0, y: -10 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          animate={{ opacity: 1, y: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          variant="primary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      size="lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  isLoading={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={loading || !username || !password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Iniciar Sesion
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-center text-xs text-gray-500 mt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Usuario: <strong>admin</strong> | Contrasena: <strong>12345</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
